author = "Gizmo"
description = "Hyperate Plugin"
homepage = "https://github.com/project-vrcat/vrchat-osc-manager-plugins/tree/main/hyperate-plugin"
name = "hyperate-plugin"
version = "0.0.2"

[entrypoint]
args = ["dist/hyperate-plugin.js"]
executable = "node.exe"
