author = "Gizmo"
description = "Pulsoid Plugin"
homepage = "https://github.com/project-vrcat/vrchat-osc-manager-plugins/tree/main/pulsoid-plugin"
name = "pulsoid-plugin"
version = "0.0.1"

[entrypoint]
args = ["run", "--allow-env", "--allow-net", "pulsoid-plugin.js"]
executable = "deno.exe"
