name = "hyperate-plugin-deno"
version = "0.0.1"
author = "Gizmo"
description = "Hyperate Plugin Deno"
homepage = "https://github.com/project-vrcat/vrchat-osc-manager-plugins/tree/main/hyperate-plugin-deno"

[entrypoint]
args = ["run", "--allow-env", "--allow-net", "--unstable", "hyperate-plugin.js"]
executable = "deno.exe"
